name: judoscale-sidekiq tests
defaults:
  run:
    working-directory: judoscale-sidekiq
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - Gemfile
          - Gemfile-sidekiq-7
          - Gemfile-sidekiq-6
          - Gemfile-sidekiq-5
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
        exclude:
          # Sidekiq 8.0 requires Ruby 3.2
          - gemfile: Gemfile
            ruby: "3.1"
          - gemfile: Gemfile
            ruby: "3.0"
          - gemfile: Gemfile
            ruby: "2.7"
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/judoscale-sidekiq/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs bundle install and caches installed gems automatically
      - run: bundle exec rake
