name: judoscale-resque tests
defaults:
  run:
    working-directory: judoscale-resque
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - Gemfile
          - Gemfile-resque-2
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
          - "4.0"
        exclude:
          - gemfile: Gemfile
            ruby: "2.7" # resque 3 dropped support to Ruby 2.7
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/judoscale-resque/${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup default Bundler for Ruby <= 3.0
        if: ${{ matrix.ruby <= '3.0' }}
        run: echo "BUNDLER_VERSION=2.4.22" >> $GITHUB_ENV
      - name: Setup default Bundler for Ruby > 3.0 & <= 3.1
        if: ${{ matrix.ruby > '3.0' && matrix.ruby <= '3.1' }}
        run: echo "BUNDLER_VERSION=2.6.9" >> $GITHUB_ENV
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs bundle install and caches installed gems automatically
          bundler: ${{ env.BUNDLER_VERSION || 'Gemfile.lock' }}
      - run: bundle exec rake
